### ISSUE TITLE
Testear el ejercicio Loop

### ISSUE THREAD

**Issue by amarrerod** [ULL-MII-CA-1819/01-high-order-function-marreA#1]
**Enunciado:**
>  **Your own loop**
> Write a higher-order function loop that provides something like a for loop statement. It takes a value, a test function, an update function, and a body function. Each iteration, it first runs the test function on the current loop value and stops if that returns false. Then it calls the body function, giving it the current value. Finally, it calls the update function to create a new value and starts from the beginning.
> 
> When defining the function, you can use a regular loop to do the actual looping.
> 
> Your code here.
> 
> loop(3, n => n > 0, n => n - 1, console.log);
>  → 3
>  → 2
>  → 1 
> 

Nuestra solución propuesta: 
https://github.com/ULL-MII-CA-1819/01-high-order-function-marreA/blob/918814087f16ad3faf96482af19042001408f164/loop.js#L14-L21

Y el problema que tenemos es, ¿qué tipo de test podemos hacer para comprobar el funcionamiento de la función?. En el ejemplo se invoca con la función _console.log_, se podría usar una función que retornara algún valor numérico pero el enunciado no dice que hagamos eso. 😕 
@crguezl @alu0100693737

**Comment by crguezl** [comment]
Hola @marreA y @alu0100693737.


¡Muy buena pregunta! 👍 
Perdonen la tardanza en contestar. 

Sólo cambiaría la condición del `while` ya que la igualdad es redundante y quizá haría local el `value`:

```js
loop = (value, test, update, body) => {
   let value = value;
    while(test(value)){
        body(value);
        value = update(value);
    } 
};
```
Esta es otra solución:

```js
function loop(start, test, update, body) {
  for (let value = start; test(value); value = update(value)) {
    body(value);
  }
}
```
> Y el problema que tenemos es, ¿qué tipo de test podemos hacer para comprobar el funcionamiento de la función?. En el ejemplo se invoca con la función _console.log_, se podría usar una función que retornara algún valor numérico pero el enunciado no dice que hagamos eso. 😕

La solución *clásica* a este problema es usar stubbing. 

La idea del "Stubbing" es *envolver* la función llamada para que haga lo que queremos.
Aquí un ejemplo de como envolvemos `console.log`:

```js
let stripAnsi = require("strip-ansi"); // console tests failing in Travis due to ANSI escapes
let insp = require("util").inspect;
let ins = (x) => insp(x, {depth:null});
var fs = require('fs');

var should = require("should");
let sinon = require('sinon');
let testConsole = require("test-console");
let expect = require('chai').expect;
const assert = require('assert');

var eggvm = require('../lib/eggvm.js');

describe('Eggvm', function() {
  describe("run", function() {
    let originalLog;
    let output = [];
    beforeEach(function() {
      originalLog = console.log;
      console.log = function (...args) { 
        originalLog(...args); 
        output.push(...args);
        return args; 
      };
    });
    // test code here
    afterEach(function() {
      console.log = originalLog;
      output = [];
    });

    /* ... more code ... */

   it("testing if.egg with mocking of console.log", function() {
       let program = fs.readFileSync('examples/if.egg', 'utf8');
       let r = eggvm.run(program);
       r.should.eql(5);
       output.should.be.deepEqual([ 5 ]);
    });
```
Miren estos enlaces:

* Tests. Mocking and Stubbing
    * [Sinon API](http://sinonjs.org/releases/v1.17.7/)
    * [Side effects of stubbing console in tests](https://gyandeeps.com/console-stubbing/)
    * [Unit Test like a Secret Agent with Sinon.js](http://elijahmanor.com/unit-test-like-a-secret-agent-with-sinon-js/) by Elijah Manor
